# Generated by Django 3.1.6 on 2021-02-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artistRegion',
        ),
        migrations.RemoveField(
            model_name='item',
            name='region',
        ),
        migrations.AddField(
            model_name='artist',
            name='region',
            field=models.CharField(choices=[('M', 'Michoacan'), ('J', 'Jalisco'), ('O', 'Oaxaca')], default=30, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='hours',
            field=models.FloatField(default=300),
            preserve_default=False,
        ),
    ]
