# Generated by Django 3.1.6 on 2021-02-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210217_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='region',
            new_name='artistRegion',
        ),
    ]
