# Generated by Django 3.1.6 on 2021-02-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210217_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(),
        ),
    ]
