# Generated by Django 3.1.6 on 2021-02-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210217_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('X', 'Wixarika (Huichol) Art')], default=2, max_length=2),
            preserve_default=False,
        ),
    ]
