# Generated by Django 3.1.7 on 2021-03-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shippingaddress_holder_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_charge_id',
            new_name='charge_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
