# Generated by Django 3.1.7 on 2021-03-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210315_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, max_digits=64),
        ),
    ]
