# Generated by Django 3.1.6 on 2021-02-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210218_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artistCommunity',
            field=models.CharField(choices=[('W', 'Wixarika (Huichol)')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='artistRegion',
            field=models.CharField(choices=[('M', 'Michoacan'), ('J', 'Jalisco'), ('C', 'Chiapas'), ('O', 'Oaxaca')], max_length=2),
        ),
    ]
