# Generated by Django 3.1.6 on 2021-02-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210218_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artistCommunity',
            field=models.CharField(choices=[('W', 'Wixarika (Huichol)'), ('P', 'Purepecha')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('X', 'Wixarika (Huichol) Art'), ('P', 'Purepecha Burnished Clay')], max_length=2),
        ),
    ]
