# Generated by Django 3.1.7 on 2021-03-16 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210316_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='charge_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='holder_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
