# Generated by Django 3.1.6 on 2021-02-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210219_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartheader',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
