# Generated by Django 3.1.7 on 2021-03-17 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210317_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='cartbody',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cartbody'),
            preserve_default=False,
        ),
    ]
