# Generated by Django 3.1.7 on 2021-03-17 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_shippingaddress_cartbody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='cartbody',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='CartHeader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cartheader'),
            preserve_default=False,
        ),
    ]
