# Generated by Django 3.1.6 on 2021-02-26 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210226_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='artType',
        ),
    ]
