# Generated by Django 3.1.7 on 2021-03-24 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_category_categoryphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=100)),
                ('subcategoryPhoto', models.FileField(upload_to='categories')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='artType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subcategory'),
        ),
    ]
