# Generated by Django 3.1.7 on 2021-03-24 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210324_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.subcategory'),
            preserve_default=False,
        ),
    ]
