# Generated by Django 3.1.7 on 2021-03-24 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210324_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategoryPhoto',
        ),
    ]
