# Generated by Django 3.1.7 on 2021-03-25 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_subcategory_subcategoryphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='artType',
            new_name='subcategory',
        ),
    ]
