# Generated by Django 3.1.7 on 2021-03-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210325_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content1',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='content2',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='subtitle',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teammemeber',
            name='job',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='teammemeber',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
