# Generated by Django 3.1.7 on 2021-03-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210325_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content1',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='about',
            name='content2',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=5000),
        ),
    ]
