# Generated by Django 3.1.7 on 2021-03-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210325_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='content1',
            new_name='firstContent',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='content2',
            new_name='secondContent',
        ),
        migrations.AddField(
            model_name='about',
            name='contentPhoto',
            field=models.FileField(default=1, upload_to='about_photo'),
            preserve_default=False,
        ),
    ]
