# Generated by Django 3.1.7 on 2021-03-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210325_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemeber',
            name='profile',
            field=models.FileField(default=1, upload_to='profile'),
            preserve_default=False,
        ),
    ]
