# Generated by Django 3.1.7 on 2021-04-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_teammemeber_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='stripe_customer_id',
            new_name='openpay_customer_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='one_click_purchasing',
        ),
    ]
