# Generated by Django 3.1.7 on 2021-04-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210424_1944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
