# Generated by Django 3.1.7 on 2021-04-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='openpay_customer_id',
            new_name='token',
        ),
    ]
